In [2]:
import pandas as pd
from tensorflow.keras import layers,models
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder,MinMaxScaler

In [3]:
df = pd.read_csv("D:/Files/heart.csv")
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [4]:
df1 = df.copy()
df1 = df1.drop(["FastingBS","RestingECG","MaxHR","ST_Slope"],axis = 1)
df1.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,ExerciseAngina,Oldpeak,HeartDisease
0,40,M,ATA,140,289,N,0.0,0
1,49,F,NAP,160,180,N,1.0,1
2,37,M,ATA,130,283,N,0.0,0
3,48,F,ASY,138,214,Y,1.5,1
4,54,M,NAP,150,195,N,0.0,0

In [5]:
df1.isna().sum()

Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
ExerciseAngina    0
Oldpeak           0
HeartDisease      0
dtype: int64

In [6]:
m = MinMaxScaler()
l = ["Age","RestingBP","Cholesterol","Oldpeak"]
for i in l:
    df1[i] = m.fit_transform(df1[[i]])
df1.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,ExerciseAngina,Oldpeak,HeartDisease
0,0.244898,M,ATA,0.70,0.479270,N,0.295455,0
1,0.428571,F,NAP,0.80,0.298507,N,0.409091,1
2,0.183673,M,ATA,0.65,0.469320,N,0.295455,0
3,0.408163,F,ASY,0.69,0.354892,Y,0.465909,1
4,0.530612,M,NAP,0.75,0.323383,N,0.295455,0

In [7]:
df2 = df1.copy()

# Initialize the OneHotEncoder
ohe = OneHotEncoder(drop='first', sparse_output=False)

# Columns to be encoded
ll = ["Sex", "ExerciseAngina", "ChestPainType"]

for i in ll:
    # Transform and create DataFrame for each column
    transformed_data = ohe.fit_transform(df2[[i]])
    transformed_df = pd.DataFrame(transformed_data, columns=ohe.get_feature_names_out([i]))

    # Concatenate with the original DataFrame
    df2 = pd.concat([df2.reset_index(drop=True), transformed_df.reset_index(drop=True)], axis=1)

df2.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,ExerciseAngina,Oldpeak,HeartDisease,Sex_M,ExerciseAngina_Y,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA
0,0.244898,M,ATA,0.70,0.479270,N,0.295455,0,1.0,0.0,1.0,0.0,0.0
1,0.428571,F,NAP,0.80,0.298507,N,0.409091,1,0.0,0.0,0.0,1.0,0.0
2,0.183673,M,ATA,0.65,0.469320,N,0.295455,0,1.0,0.0,1.0,0.0,0.0
3,0.408163,F,ASY,0.69,0.354892,Y,0.465909,1,0.0,1.0,0.0,0.0,0.0
4,0.530612,M,NAP,0.75,0.323383,N,0.295455,0,1.0,0.0,0.0,1.0,0.0

In [14]:
df2 = df2.drop(['Sex','ChestPainType','ExerciseAngina'],axis = 1)
df2.head()

,Age,RestingBP,Cholesterol,Oldpeak,HeartDisease,Sex_M,ExerciseAngina_Y,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA
0,0.244898,0.70,0.479270,0.295455,0,1.0,0.0,1.0,0.0,0.0
1,0.428571,0.80,0.298507,0.409091,1,0.0,0.0,0.0,1.0,0.0
2,0.183673,0.65,0.469320,0.295455,0,1.0,0.0,1.0,0.0,0.0
3,0.408163,0.69,0.354892,0.465909,1,0.0,1.0,0.0,0.0,0.0
4,0.530612,0.75,0.323383,0.295455,0,1.0,0.0,0.0,1.0,0.0

In [16]:
x = df2.drop("HeartDisease",axis = 1)
y = df2.HeartDisease
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 45)

In [18]:
x_train.shape

(734, 9)

In [20]:
y_train.shape

(734,)

In [30]:
model = models.Sequential([
    layers.Flatten(input_shape=(9,)),
    layers.Dense(128,activation = 'relu'),
    layers.Dense(84,activation = 'relu'),
    layers.Dense(64,activation = 'relu'),
    layers.Dense(32,activation = 'relu'),
    layers.Dense(16,activation = 'relu'),
    layers.Dense(8,activation = 'relu'),
    layers.Dense(4,activation = 'relu'),
    layers.Dense(2,activation = 'relu'),
    layers.Dense(1,activation = 'softmax')
])

C:\Users\madda\AppData\Roaming\Python\Python312\site-packages\keras\src\layers\reshaping\flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

In [32]:
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [38]:
model.fit(x_train,y_train,epochs = 50, validation_data=(x_test,y_test),validation_split=0.6)

Epoch 1/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5635 - loss: 0.4436 - val_accuracy: 0.5054 - val_loss: 0.6002
Epoch 2/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5798 - loss: 0.4725 - val_accuracy: 0.5054 - val_loss: 0.6019
Epoch 3/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5460 - loss: 0.4574 - val_accuracy: 0.5054 - val_loss: 0.5636
Epoch 4/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5955 - loss: 0.4357 - val_accuracy: 0.5054 - val_loss: 0.5755
Epoch 5/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5584 - loss: 0.4449 - val_accuracy: 0.5054 - val_loss: 0.5723
Epoch 6/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5568 - loss: 0.4434 - val_accuracy: 0.5054 - val_loss: 0.5795
Epoch 7/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5670 - loss: 0.4323 - val_accuracy: 0.5054 - val_loss: 0.5703
Epoch 8/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5545 - loss: 0.4363 - val_accuracy: 0.5054 - val_loss: 0.5594
Epoch 9/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5629 - loss: 0.4183 - val_accuracy: 0.5054 - val_loss: 0.5876
Epoch 10/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5552 - loss: 0.4080 - val_accuracy: 0.5054 - val_loss: 0.5490
Epoch 11/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5724 - loss: 0.4293 - val_accuracy: 0.5054 - val_loss: 0.5516
Epoch 12/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5682 - loss: 0.4144 - val_accuracy: 0.5054 - val_loss: 0.5423
Epoch 13/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5677 - loss: 0.4479 - val_accuracy: 0.5054 - val_loss: 0.5937
Epoch 14/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5557 - loss: 0.4173 - val_accuracy: 0.5054 - val_loss: 0.5556
Epoch 15/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5748 - loss: 0.4375 - val_accuracy: 0.5054 - val_loss: 0.5743
Epoch 16/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6071 - loss: 0.4222 - val_accuracy: 0.5054 - val_loss: 0.5500
Epoch 17/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5688 - loss: 0.3982 - val_accuracy: 0.5054 - val_loss: 0.5518
Epoch 18/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5679 - loss: 0.4047 - val_accuracy: 0.5054 - val_loss: 0.5908
Epoch 19/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5756 - loss: 0.4807 - val_accuracy: 0.5054 - val_loss: 0.5544
Epoch 20/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5734 - loss: 0.4028 - val_accuracy: 0.5054 - val_loss: 0.5668
Epoch 21/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5598 - loss: 0.4193 - val_accuracy: 0.5054 - val_loss: 0.5754
Epoch 22/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5546 - loss: 0.4288 - val_accuracy: 0.5054 - val_loss: 0.5553
Epoch 23/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5808 - loss: 0.4020 - val_accuracy: 0.5054 - val_loss: 0.5474
Epoch 24/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5581 - loss: 0.3786 - val_accuracy: 0.5054 - val_loss: 0.5419
Epoch 25/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5687 - loss: 0.3994 - val_accuracy: 0.5054 - val_loss: 0.5865
Epoch 26/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5646 - loss: 0.3803 - val_accuracy: 0.5054 - val_loss: 0.5497
Epoch 27/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5494 - loss: 0.3954 - val_accuracy: 0.5054 - val_loss: 0.5336
Epoch 28/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5751 - loss: 0.4155 - val_accuracy: 0.5054 - val_loss: 0.5456
Epoch 29/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5460 - loss: 0.3907 - val_accuracy: 0.5054 - val_loss: 0.5193
Epoch 30/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5463 - loss: 0.3982 - val_accuracy: 0.5054 - val_loss: 0.5452
Epoch 31/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5753 - loss: 0.4028 - val_accuracy: 0.5054 - val_loss: 0.5564
Epoch 32/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5985 - loss: 0.4076 - val_accuracy: 0.5054 - val_loss: 0.5457
Epoch 33/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5589 - loss: 0.4065 - val_accuracy: 0.5054 - val_loss: 0.5401
Epoch 34/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5554 - loss: 0.3675 - val_accuracy: 0.5054 - val_loss: 0.5426
Epoch 35/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5756 - loss: 0.4155 - val_accuracy: 0.5054 - val_loss: 0.5380
Epoch 36/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5526 - loss: 0.3976 - val_accuracy: 0.5054 - val_loss: 0.5649
Epoch 37/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5676 - loss: 0.3883 - val_accuracy: 0.5054 - val_loss: 0.5446
Epoch 38/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5804 - loss: 0.3795 - val_accuracy: 0.5054 - val_loss: 0.5295
Epoch 39/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5397 - loss: 0.3693 - val_accuracy: 0.5054 - val_loss: 0.5456
Epoch 40/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5865 - loss: 0.3708 - val_accuracy: 0.5054 - val_loss: 0.5420
Epoch 41/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5436 - loss: 0.3508 - val_accuracy: 0.5054 - val_loss: 0.5306
Epoch 42/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5624 - loss: 0.3969 - val_accuracy: 0.5054 - val_loss: 0.5280
Epoch 43/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5859 - loss: 0.3822 - val_accuracy: 0.5054 - val_loss: 0.5616
Epoch 44/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5811 - loss: 0.3664 - val_accuracy: 0.5054 - val_loss: 0.5341
Epoch 45/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5658 - loss: 0.3706 - val_accuracy: 0.5054 - val_loss: 0.5519
Epoch 46/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5567 - loss: 0.3776 - val_accuracy: 0.5054 - val_loss: 0.5478
Epoch 47/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5606 - loss: 0.4064 - val_accuracy: 0.5054 - val_loss: 0.5443
Epoch 48/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5923 - loss: 0.3816 - val_accuracy: 0.5054 - val_loss: 0.5620
Epoch 49/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5457 - loss: 0.3604 - val_accuracy: 0.5054 - val_loss: 0.5503
Epoch 50/50
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5371 - loss: 0.3907 - val_accuracy: 0.5054 - val_loss: 0.5380

In [40]:
loss,accuracy = model.evaluate(x_test,y_test)
print(f"loss:{loss}\naccuracy:{accuracy}")

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4598 - loss: 0.5123
loss:0.5380011796951294
accuracy:0.5054348111152649